### ISSUE TITLE
Improve torrent search 

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#140]
- [x] client icons
- [x] add form like nzbsearch?
- [ ] categories?
- [x] make table scrollable in tablet/phone view
- [x] fix popover icon name..
- [x] add ptp
- [x] add rarbg
strike ssl issues see https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

**Comment by Hellowlol** [comment]
@raysguy Can you make a icon of http://static.passthepopcorn.me/static/common/touch-icon-iphone.png like you have done with the other torrent sites?

**Comment by thatbritguy** [comment]
Yeah that’s no problem :)

**Comment by Morphy99** [comment]
Torrent search doesnt work at all for me:
2015-08-13 23:43:04 cherrypy.error.47669144 ERROR   [13/Aug/2015:23:43:04] HTTP Traceback (most recent call last):
2015-08-13 23:43:04 modules.torrentsearch   ERROR   Failed to fetch https://torrentapi.org/pubapi_v2.php?mode=search&app_id=HTPCMANAGER&format=json_extended&search_string=the+fauns&token=None&ranked=0&sort=seeders&json_extended=1&limit=100 [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-08-13 23:43:04 modules.torrentsearch   ERROR   No token list indices must be integers, not str
2015-08-13 23:43:04 modules.torrentsearch   ERROR   Failed to fetch https://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=HTPCMANAGER&token=None&ranked=0&sort=seeders&json_extended=1&limit=100 [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
2015-08-13 23:43:03 modules.torrentsearch   INFO    Rarbg searching for the fauns

Maybe because most sites are blocked in uk? Could we add a proxy list?

**Comment by Hellowlol** [comment]
Seems like a ssl error. But just paste that url in your browser to see if your blocked by your isp.See https://github.com/SickGear/SickGear/wiki/Upgrade-SSL for possible solutions regarding ssl

**Comment by Morphy99** [comment]
Ok will look into that, thanks. Is there any chance of getting proxies in place for the public trackers? Or a way to enter a mirror?

**Comment by Hellowlol** [comment]
Not atm. If you give me a list of mirrors for each provider I'll look into it.

**Comment by Morphy99** [comment]
Thanks, getting results now :)

**Comment by Hellowlol** [comment]
I'm happy it's works for you but I haven't done anything :p

**Comment by Morphy99** [comment]
Weird, this stopped working again a few mins ago and is now working again. I'm not seeing anything in the log either, is there a debug function? I think this may relate to a previous issue (https://github.com/Hellowlol/HTPC-Manager/issues/79) where I highlighted there is no feedback for a failed search. Neither is there for a no results search.

**Comment by Hellowlol** [comment]
Some of the api has limits, so you only can do x search in y time frame. You can change the loglevel to debug and check the log after a search (restart) required

**Comment by Morphy99** [comment]
Ah yes maybe thats it. Would be handy to have a timeout message to avoid user confusion?

**Comment by Hellowlol** [comment]
Not really, if your missing results you should add more providers. I can add a message if none are found by all providers

**Comment by Hellowlol** [comment]
Come to think about it. It already supports this.

![image](https://cloud.githubusercontent.com/assets/1214134/9416155/2af53b2c-4844-11e5-8dce-b0349c8e5c4d.png)

**Comment by Hellowlol** [comment]
@Morphy99 What providers do you use?

**Comment by Morphy99** [comment]
YTS KAT & Strike. I haven't seen that message... Actually yes it does appear with no results. It must be a timeout then I'm seeing.

**Comment by Hellowlol** [comment]
What do you search on?

**Comment by Morphy99** [comment]
How do you mean?

**Comment by Hellowlol** [comment]
What do your search for in the torrent module when you get no results and no message about empty results?  I can't seem to recreate your issue

**Comment by Morphy99** [comment]
"the fauns" it seems to be intermittent though. I have debug level selected in log but can't see anything.
