### ISSUE TITLE
Headphones

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#24]
@kooimens Can you try this https://github.com/Hellowlol/HTPC-Manager/tree/headphones and report all errors and kinks? If you feel anything is missing let me know.

https://github.com/styxit/HTPC-Manager/pull/133

**Comment by kooimens** [comment]
Nice! Thanks for getting into this. The history tab is now working! The next things could be better or can be added:

1. Having the ability to search for albums as well, next to the ability to search for artists, would be great. This is especially useful when performing a search for albums with album artist = various artists.

2. The history tab - status can have 3 values: Snatched, unprocessed and processed. They all have the color orange. I think snatched should be orange, processed green and unprocessed red. 
![1](https://cloud.githubusercontent.com/assets/3150962/5995223/fb4ce554-aa8d-11e4-9f5b-d491fb9329ca.jpg)

3. In some cases artists don't have a "Last album". That is called "None (none)". However, it should not be a link, because it returns an error when clicking it.
![2](https://cloud.githubusercontent.com/assets/3150962/5995209/a5008962-aa8d-11e4-8964-d8a858ac6b35.jpg)
![3](https://cloud.githubusercontent.com/assets/3150962/5995210/abc99c20-aa8d-11e4-92b7-b596777ea27d.jpg)

4. Artist and album thumb could be added. It looks like there is some space on the left side when opening an album/artist. 
![4](https://cloud.githubusercontent.com/assets/3150962/5995320/54a53870-aa90-11e4-8a12-49d68570a52d.jpg)
![5](https://cloud.githubusercontent.com/assets/3150962/5995323/59e1d898-aa90-11e4-8dff-a282ebd697ca.jpg)

5. Default sort order of an album should be on track#. Right now, it looks like individual tracks are just shown randomly.
![6](https://cloud.githubusercontent.com/assets/3150962/5995351/f5d64392-aa90-11e4-8009-f7d2e392e79d.jpg)

I think these are the most important issues for now. I will do some more extensive testing this week and try some other devices/browsers as well.

**Comment by Hellowlol** [comment]
Thanks for the feedback. Ill add/fix your comments. What was the url so headphones was faster again?

**Comment by kooimens** [comment]
musicbrainz-mirror.eu:5000

**Comment by Hellowlol** [comment]
Thanks

**Comment by Hellowlol** [comment]
@kooimens I was looking at the api, do you want something on the dash aswell? If thats the case what? Do you want a own tab where you get suggestions about artists that you might like?

**Comment by kooimens** [comment]
I think a list of the wanted albums on dash would be great! Just like sickbeard and couchpotato. I personally don't use the suggestions of headphones, it really sucks. To be honest, a suggestions tab with the imdb top 10 / movies you might like would be worth the work much more, especially for other users. But maybe you can ping some of the others who requested the headphones module to ask how they think about a suggestions tab?

**Comment by Hellowlol** [comment]
Fuck em, I'm making this for you, if your not interested I'll pass. I got other shit to do

**Comment by kooimens** [comment]
Haha ok:D! Thanks!

**Comment by kooimens** [comment]
And I really like to help you where I can to help the project alive!;) Here are my first test results:

1. I'm on a 1680x1050 resolution right now and the headphones module is only using about 60% of the HTPC-Manager with, where the couchpotato and sickrage modules are the using the full width. 

2. The album/artist searcher is throwing back a lot of errors. And the button 'Add Artist' doesn't apply anymore if we add an album instead of an artist. I think just 'Add' would be enough. It returns search results (for albums and artists) and adds artists in the end (after clicking all the 'ok' errors) but refuses to add albums (after searching for it and hitting 'ok' on all the errors).
![1](https://cloud.githubusercontent.com/assets/3150962/6027029/745f3c06-abdf-11e4-8a24-afa5278bf17b.jpg)
![2](https://cloud.githubusercontent.com/assets/3150962/6027026/729d7932-abdf-11e4-860d-5b5287fa3276.jpg)
![3](https://cloud.githubusercontent.com/assets/3150962/6027025/729bf26a-abdf-11e4-8b83-2b82c8873026.jpg)

3. The artist thumbs are not showed and I think it's better to use the album front cover instead of 'fan-art' size, because that will look better.
![4](https://cloud.githubusercontent.com/assets/3150962/6027122/3fc87060-abe0-11e4-9cee-5fa97d4a1779.jpg)
4. For the albums where an album art is not present, HP uses this: 
![folder](https://cloud.githubusercontent.com/assets/3150962/6027137/64644412-abe0-11e4-9809-a27660efb0b7.png)
Maybe, you can use that as well?

5. Track sorting is fixed!

6. Last but not least, is it possible to 'upgrade' the artist tab? W've got a lot of space in there, because it only shows album name and 'status'. Maybe it's an idea to add the artist thumb on the front of the artist name as well? Just like HP does:
![6](https://cloud.githubusercontent.com/assets/3150962/6027348/a7b80d60-abe1-11e4-8ecc-dec37df07f2d.jpg)

Same for wanted albums tab:
![7](https://cloud.githubusercontent.com/assets/3150962/6027373/dc58350e-abe1-11e4-9bb3-cc47db8259ef.jpg)
That would be really awesome! Then it's got the same feel and look as couch and sickrage has.

**Comment by Hellowlol** [comment]
@kooimens Regarding: The artist thumbs are not showed and I think it's better to use the album front cover instead of 'fan-art' size, because that will look better. 

Im not sure i like any of the solutions like they are today, im thinking dropping the entire banner. Im thinking about using a poster with album cover. Any thoughts? and btw, i have added some more stuff, let me know if you find any errors or want anything changed

@edru Here is your chance to chip in regarding changes. Once im done im never gonna touch this again (except for bugs)

**Comment by edru** [comment]
Cool. Im at work for another hour, but will sync it up when I get home and let you know. If I'm to late, then oh well! Thanks for the heads up.

**Comment by Hellowlol** [comment]
No worries, you won't be to late it's not like it's getting merges today anyways. I'd still like to hear your thoughts whenever you get some spare time.

**Comment by kooimens** [comment]
Damn! Going fast:D

1. Adding an artist is no problem. HP picks it up immediately. However, it refuses to add an album. This is the logging from HP:
![1](https://cloud.githubusercontent.com/assets/3150962/6033195/0345ea18-ac13-11e4-83b3-ab69f76d85ee.jpg)

2. When doing an album search, the name and release date of the album is returned. Since there are many albums with the same name it would be useful to have an artist name next to the album that is found. Perhaps with the album name in bold? A full date is useless as well, only the release year would be much better to leave some space for the artist name. 

3. Fix for width seems to be working, but i'm on a smaller device right now so will confirm that later.

4. Colors on history tab: fixed! Looks good. One more thing, I think we should make status 'wanted' (for album) blue and status 'snatched' (for the album, same as for the history list) orange. Then we have skipped (grey), processed/downloaded (green), snatched (orange), unprocessed (red). Artist = active or paused (green or red) is fine to me.

5.1 If you ask me, a poster is definetaley the way to go! It suits the way HTPC and the other modules are build. It was on my mind as well. Furthermore, the only information that is really useful regarding the artist-tab is his or her name;). I don't care about status or last album/release date. Then you can easily go for artist thumb = poster followed by artist name.  

5.2 Same as for the albums wanted-tab. With the only difference that we have to show the album name next to artist name. If that's to much, in combination with a poster view, then I would drop artist name, but I'm not sure about that. 

5.3 Dropping the banner when viewing an album or artist would also be better. Using the space on the left-top corner of the artist/album view to fit in the thumb is preferable.

**Comment by kooimens** [comment]
Hmm, I think I changed my mind regarding the view of the wanted-tab. I think for the wanted-tab a list with the release date, artist name, album name and a button to remove it from the wanted list together with a album thumb is the way to go, because the user want to know the exact release in one view for a wanted album

**Comment by Hellowlol** [comment]
@blindpet pinging as you have requested hp

**Comment by blindpet** [comment]
Awesome, hopefully I will have time to test, SickRage and Sonarr were up too?

**Comment by Hellowlol** [comment]
Sickrage and sonar are already included in my fork.

**Comment by blindpet** [comment]
Sweet, any limitations I should be aware of when I test it?

**Comment by Hellowlol** [comment]
Not really. In hp there are some bugs like cant add a release but ill get to that.

**Comment by kooimens** [comment]
@Hellowlol The problem with adding an album is indeed related to the fact that you're using artistID instead of albumID. I checked by doing a search on MusicBrainz with the ID from the error HP log. It returns an artist.

**Comment by Hellowlol** [comment]
Great, that's a easy fix. All the ids look the same (compared to tvdbid vs imdbid)

**Comment by Hellowlol** [comment]
What left to do now is:
- fix thumb img
- fix status in artist view
- finish reboot, restart upgrade
- secure the module
- remove print and console.log

After its merges and if I'm bored I might add manual download, choose release

**Comment by blindpet** [comment]
I just got time to test this and don't see Headphones anywhere, do I need to switch branch?

**Comment by Hellowlol** [comment]
Yeah, its not merged yet. Use the headphones branch

**Comment by blindpet** [comment]
Ok cool, when do you plan to merge? I will be making an installation guide for this when it goes live :)

**Comment by Hellowlol** [comment]
This weekend, think i get some spares time tomorrow.

**Comment by Hellowlol** [comment]
@blindpet let me know if you have any questions regarding the setup.

**Comment by blindpet** [comment]
Will do, just wrote the guide for Windows and all seems to be working. I am ready to post it over the weekend when your changes are merged. Thanks for your work on this, HTPC Manager is finally updated for 2015 :)

**Comment by Hellowlol** [comment]
Does that include the vnstat module aswell?

**Comment by blindpet** [comment]
Just a basic install, trying to get psutil to work, vnstat is for Windows too?

**Comment by blindpet** [comment]
psutil all working, vnstat seems to be for Linux too though there are other cross-platform alternatives like munin and ntop.

**Comment by Hellowlol** [comment]
I don't think so, but the idea is to install vnstat on your router so your can measure all your bandwidth usage. I don't think many will use the module. I made it cus it was requested. I just think it pretty. Lol

**Comment by blindpet** [comment]
I wish I could see it :P do only openwrt/ddwrt routers support vnstat?

**Comment by Hellowlol** [comment]
You can see a wip image here. http://forum.kodi.tv/showthread.php?tid=126297&page=60. Thinks so :(

**Comment by Hellowlol** [comment]
@kooimens @edru @blindpet Any chance you can test it again? Is it ok, working as it should, any visual changes you want done? This is gonna be the last time i ask before clean up and merge :)

**Comment by blindpet** [comment]
My test environment is all fucked up atm so can't really do any tests and my friend I had test the guide doesn't run Headphones. Sorry I can't be of more help

**Comment by Hellowlol** [comment]
Thats fine. Neader do i lol. Thanks anyway

**Comment by kooimens** [comment]
1. The images on the album and artist detail page looks a bit stretched. If I take a look at the headphones pictures itself they seem to have an equal width and length (250x250). To make it look better, maybe you should go for the square-format instead of the poster-look. 

2. On the artist-tab, the images don't have the same size. 
![1](https://cloud.githubusercontent.com/assets/3150962/6099120/ce27f268-aff0-11e4-975e-626dfe5280ec.jpg)

3. Every status has an icon attached to it. However, for "unprocessed" it is lacking. Some kind of an error icon would finish it.

4. On the wanted-tab, the 'search for' and 'delete' button should show some text when mouseover. E.g. 'search for album' and 'delete album from wanted list'. Maybe you can ask to confirm the action (especially for deleting albums)? 

5. On the albums tab of an artist-page I can see an extra icon for, I don't know, deleting an album? I think deleting things in Headphones is only useful for deleting album from the wanted list. Beyond that, I wouldn't use a delete button for any other things. Furthermore, a mousover shows 'search for album', which is of course not the case.
![3](https://cloud.githubusercontent.com/assets/3150962/6099201/c2817ce8-aff2-11e4-9980-c2aa248f4b08.jpg)

6. I didn't notice the dropdown menu on the mainpage of the headphones module before. Is it possible to enable/disable each of the options within the dropdown menu through a check/uncheck box on the settings-page? It's some kind of a future request, but I think it can be extremely handy to have. The same goes for the sickrage module, where I can see a dropdown menu as well. The problem is, I don't want my users, nor myself to be able to shutdown or restart anything. I use a LDAP backend with an apache logon, so I think enabling/disabling it for certain users within htpc would not be an option as I'm not using it. I'm not using the post-process option at all, because I make use of the nzbtomedia scripts. It's up to you, of course, but I think it can useful to have something like that build-in to make HTPC-Manager more customisable (and bring it to other modules in future).

I think that's it. Thanks for all your work!

**Comment by kooimens** [comment]
Weird shit. Didn't receive a notification. I cleared the cache on the general settings tab, nothing changed. I will have a look at #17 and do some tests.

**Comment by Hellowlol** [comment]
I think thats because i edited your post. The images in artist list is ok on my screen.

![image](https://cloud.githubusercontent.com/assets/1214134/6113379/2b18d4be-b097-11e4-8977-70b2cab897a8.png)

**Comment by kooimens** [comment]
The delete button didn't work out. Same for deleting browser cookies and restart, disable/enable module and in the end even a hard remove of all the userdata. Nothing changed...

**Comment by Hellowlol** [comment]
@kooimens Have you installed pil?

**Comment by kooimens** [comment]
Now I have;) and it's fixed! thanks

**Comment by Hellowlol** [comment]
@kooimens @edru @blindpet Its merged :)

**Comment by blindpet** [comment]
Awesome, will post guide tomorrow :)

**Comment by edru** [comment]
Thanks man. Is there a special branch I need to sync to for the push, or should the master be fine? Only asking because I'm currently on master and dont see any of the options.

**Comment by Hellowlol** [comment]
yeah, master is just synced with styxit version. If you want all features use the default branch master2

**Comment by Hellowlol** [comment]
@edru Make sure you clone/fork my repo
@kooimens I just noticed i forgot to add headphones to the dash... Its coming, i promise.

**Comment by edru** [comment]
random question, do you have a default username/password set on this? Either than or a previous config is conflicting. I deleted my previous HTPCManager folder, then cloned your branch, but cant sign in. Using what I had previously as my U/P, but doesnt seem to take it.

**Comment by Hellowlol** [comment]
Nope, might be the db, start HTPC manager with --resetauth

**Comment by edru** [comment]
Worked like a charm, thanks.

**Comment by edru** [comment]
Not sure if here is the correct place for this, but my dashboard has some empty spot. I have:

latest movies, shows, music, 
downloads, movies, empty spot
Next Aired


Not sure as to why there is a blank spot unless its torrents and there is no label or indication that the queue is empty.

**Comment by Hellowlol** [comment]
Please make a new issue with a list of enabled modules and I image. Yes they are preset.

**Comment by Hellowlol** [comment]
@blindpet Thanks you so much for make all your guides. I didn't know about nssm, great tip!
