### ISSUE TITLE
"Issues" theme moonlight

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#296]
The issues regarding this readability.

The font are to slim, i have a hard time reading alot of the text.

![image](https://cloud.githubusercontent.com/assets/1214134/9069880/49933a9e-3aec-11e5-8021-d6eb46044af9.png)
(We could change the color on the error, but still)

Da fuk? 
![image](https://cloud.githubusercontent.com/assets/1214134/9069886/5d2b48b2-3aec-11e5-8d67-1a7a9b44ebd5.png)

The next in the bars are hard to read on phones as the light level must be high (no powersave options)

There is a username in the input text.. Why is this white?
![image](https://cloud.githubusercontent.com/assets/1214134/9070101/bc44d146-3aed-11e5-8196-19768daf3cf6.png)

**Comment by thatbritguy** [comment]
Hahaha, wtf?!  What have you done to my baby?! Hahaha.  I have no idea why it looks like that - I don't see any of that at all on mine.  Where are the solid red bars coming from?  Table rows should alternate between the two shades of grey.  And I have a username and password in the settings too but the text box background is gray just like the Port and Webdir etc.

Can you try a different browser?  I just about deleted my repo this afternoon because none of the fonts in the themes were loading in Chrome but I switched to safari and it was fine.  Installed canary build of Chrome and that was fine.  After force quitting regular chrome and restarting that was fine too.

I've just tested on both safari and chrome and I can't reproduce the behaviour in your screenshots.

**Comment by Hellowlol** [comment]
As for the trs, thats because the "episodes" are missing. Ill try with the git version. This was via the source updater, but there "might be issues". Ill check the git version

**Comment by thatbritguy** [comment]
Oh crap I don't use SickRage, do all the themes look like that?  I thought other modules would behave same as Sonarr with labels for episode status.  Are the whole trs supposed to be red?

Cool, let me know what you find.  I've just tried a test environment of HTPC on my laptop which I use when working on it, and also the production version on the server.  Both working okay on latest commit.

**Comment by Hellowlol** [comment]
Ok, so i tried the git version. The white input field was fixed.

This is firefox
![image](https://cloud.githubusercontent.com/assets/1214134/9070799/eeefe190-3af1-11e5-8a9a-b76029e488ef.png)

**Comment by Hellowlol** [comment]
The red stuff is okei. I wanted to get smacked in the face if something isnt downloaded. But the issue is still with the font. Can you make a ss on how this looks on your computer with moonlight?

**Comment by Hellowlol** [comment]
I think its just a useragent thing regarding nzb.su, As for pfmonkey i have no idea.

**Comment by thatbritguy** [comment]
Okay I just installed and set up SickRage so I could see what was happening here.  Can you add the following to sickrage.css and confirm that fixes it for you?

`.table tbody tr.error td {
    color: inherit !important;
}`

**Comment by Hellowlol** [comment]
Hm fix what? the red stuff?
![image](https://cloud.githubusercontent.com/assets/1214134/9072370/0d852684-3afb-11e5-9019-543ff6d5ee90.png)

**Comment by thatbritguy** [comment]
Yeah, why are your fonts showing so thin though?  Here's screenshot of it on my chrome:

<img width="1272" alt="srtest" src="https://cloud.githubusercontent.com/assets/10825337/9072489/64aa4e2e-3af3-11e5-8514-1300af8d49a7.png">

**Comment by thatbritguy** [comment]
And this is same page on safari:

<img width="1275" alt="srtestsafari" src="https://cloud.githubusercontent.com/assets/10825337/9072561/d7740a6c-3af3-11e5-820f-c1685440ee75.png">

**Comment by Hellowlol** [comment]
I have no idea... :P Prob the same reason as my dropdowns are so square xD

**Comment by thatbritguy** [comment]
Okay I'm pretty sure this is a Windows issue.  Just set up a Windows 10 VM and tried on Microsoft Edge and Google Chrome on there and it looked like yours.  No clue why Windows should display things differently though...

EDIT - actually it still isn't as thin as yours but definitely thinner than mine.  Maybe a ClearType issue?

**Comment by Hellowlol** [comment]
Dunno, i just picked the "best" options in the cleartype settings. Can you post a pic how it looks on windows?

**Comment by Hellowlol** [comment]
@Fma965 Are you using windows as well? Can you post a ss of the moonlight theme?

**Comment by fma965** [comment]
I cant get a screenshot currently but yeah mine look like yours @hellowlol and I run Windows 10 and chrome, I did mention that this when I said my fonts look un readable on the other issue.

**Comment by Hellowlol** [comment]
Ok, so we need to find a better font. Not being able to use it on a entire platform is unacceptable.

**Comment by Hellowlol** [comment]
Bars, dropdown and text is not aligned
![image](https://cloud.githubusercontent.com/assets/1214134/9073634/f6b83a74-3b02-11e5-99bb-fd1f5a41f556.png)

**Comment by fma965** [comment]
My guess would be somesort of font compatibility issue or clear type issue

**Comment by madclicker** [comment]
IMO most of your themes are un-readable because of the font issues. 
Slate is the best after I tweaked it quite a bit. Also I'm not a big fan 
of altering the original bootstrap code. You can do everything you need 
by overriding in another script.

**Comment by Hellowlol** [comment]
This is how it looks on 
![image](https://cloud.githubusercontent.com/assets/1214134/9074036/51ee5d8a-3b06-11e5-9991-31298a7a3083.png) after i replace the font url: //fonts.googleapis.com/css?family=Josefin+Sans&subset=latin,latin-ext

**Comment by thatbritguy** [comment]
Yeah that's because the theme can no longer find the font weight it's looking for :P 
There are three themes I specifically used really light fonts (Moonlight, Plexibility and Sublime) for variety as some people prefer really light ones _cough_ _me_ _cough_! Hahaha

I found a fix for the issues Windows has with fonts which can be applied without messing up the fonts.  Add the following to base.css:

`* {
    -webkit-text-stroke: 0.35px !important;
}`

Makes a big difference.  Here's a SS of Chrome on Windows 10 after making that change:

<img width="1087" alt="windows fix" src="https://cloud.githubusercontent.com/assets/10825337/9074285/09023912-3b00-11e5-9528-8302ca39571a.png">

**Comment by fma965** [comment]
Except webkit prefixed css is only going to work for chrome, what bout Firefox, ie, edge?

**Comment by thatbritguy** [comment]
@madclicker - Slate was one of the old themes that has been removed and isn't part of the re-bootstrap themes.

**Comment by fma965** [comment]
Are you altering bootstrap code? That's really bad for future proofing, isn't using important in css bad practice unless absolutely necessary?

**Comment by Hellowlol** [comment]
I dont really see that as a issue. You more free to choose yourself. Im just happy im not doing it :P

**Comment by thatbritguy** [comment]
@Fma965 the issue is supposedly one which primarily affects webkit browsers on Windows and that's the fix people seem to have found the best. IE and their Trident engine is a whole different story and I have no plans to support those.

As for altering bootstrap code - I used the same method and techniques to compile the themes as is used by bootswatch themes (using the LESS variable and scaffolding files provided by bootstrap for customisation).  HTPC Manager uses bootstrap 2.3.2 and as such I created bootstrap 2.3.2 themes (HTPC Manager was the main motivation to create themes) so future-proofing isn't something I have to worry about.  If I find the need to create bootstrap 3 themes in future I'd start from the ground up specifically for bootstrap 3.

**Comment by fma965** [comment]
It's not and issue till you try to change stuff or want to update bootstrap version.

**Comment by fma965** [comment]
OK ignore my previous comment since you just gave me the answers, seems I mis understood  great work. It's late here so that's my excuse

**Comment by thatbritguy** [comment]
We had a whole discussion about updating to bootstrap 3 before I started doing the themes (otherwise I would have held off) but I believe @Hellowlol came to the same conclusion as me which is basically that the amount of work and problems involved in trying to update to bootstrap 3 far outweighed any potential benefits of doing so.

That's okay, I've learned a lot as I've gone through the process of making them and am still learning!  Every issue or bug that pops up is an opportunity to learn something new! :)

**Comment by Hellowlol** [comment]
@raysguy Are you planning on sending a pr to correct the errors?

**Comment by fma965** [comment]
@raysguy if you need any help with the css or html let me know.

**Comment by Hellowlol** [comment]
@Fma965 Feel free to pick a theme and go thru every module for errors :P

**Comment by thatbritguy** [comment]
I've just implemented something which should work for everyone. Just need to figure out why the settings page is error in our on me! :P

**Comment by Hellowlol** [comment]
do you get a traceback?

**Comment by thatbritguy** [comment]
Thanks @Fma965. I don't have access to every module in HTPC so just let me know if you come across anything funky. :)

**Comment by thatbritguy** [comment]
I get a whole bunch of cherry py errors.

**Comment by fma965** [comment]
Actually i got a feature request... add multiple fonts in a dropdown or by entering a google fonts URL :) i think this would be cool

**Comment by thatbritguy** [comment]
It would be cool but also a major headache to implement and maintain. Had to be really careful about fonts I chose as some have weird spacing and break everything. 

What I've been adding today though is a second variant of each theme with heavier font-weight which can be toggled on or off via a switch on the theme settings page :)

**Comment by Hellowlol** [comment]
@raysguy You can use https://github.com/Hellowlol/HTPC-Manager/blob/master2/htpc/helpers.py#L237 to return the template instead of https://github.com/Hellowlol/HTPC-Manager/blob/master2/htpc/settings.py#L40 (i wrote that helper as mako without debugging is pain.)

**Comment by fma965** [comment]
@raysguy it wouldn't be hard to implement but yeah it would be hard to maintain, maybe.. .depends on if we just told them no support with custom fonts though, loving the new option thats coming anyway :)

**Comment by thatbritguy** [comment]
Toggleable option added in PR #297 which increases font weight in all themes that weren't using heavier font weights to begin with.  Let me know how you get on with it.

**Comment by Hellowlol** [comment]
It was a lot better on mobiles at least!

**Comment by fma965** [comment]
looking much better on chrome :)

With Heavy
![GitHub Logo](http://i.imgur.com/C6ELq2m.png)

Without Heavy
![GitHub Logo](http://i.imgur.com/NpPgIPr.png)

**Comment by bakman2** [comment]
I have customised the onyx theme, I have a hard time with the default exotic fonts and their sizes and the colors. Bootstrap is a bit over the top. (I usually work with skeleton together with an icon font).

I have stripped colors from buttons and reduces font-sizes,line-heights and paddings and added the roboto font. 

![screen shot 2015-08-05 at 19 12 51](https://cloud.githubusercontent.com/assets/333960/9093665/aa02394a-3bad-11e5-8d62-bc16cc04ab80.jpg)
![screen shot 2015-08-05 at 20 01 37](https://cloud.githubusercontent.com/assets/333960/9093667/aa2216ca-3bad-11e5-8e2e-d2cc2e2994fc.jpg)
![screen shot 2015-08-05 at 20 01 50](https://cloud.githubusercontent.com/assets/333960/9093666/aa200362-3bad-11e5-9a5d-694cf44c3571.jpg)

**Comment by Hellowlol** [comment]
@bakman2 looks good. send me a pr if you want to not deal with that no every update  (give it a new name and remember to add support for extra large font weight)

**Comment by bakman2** [comment]
Thanks I have to optimise it a bit. 
Btw would it be possible to add an active state to the nav-bar ? (to highlight whatever was clicked)

**Comment by Hellowlol** [comment]
Is that really needed? Every module has a module name in the upper left corner.

**Comment by fma965** [comment]
it's not needed but would look better and shouldn't be hard to implement although i don't know python i know how to do it in php, also i really love that new "onyx based theme"

**Comment by bakman2** [comment]
just add to default.js (somewhere near the end of $(document).ready())

```
    var title = $(".content h1.page-header a:eq(0)").text().toLowerCase()
    $("#nav-"+title).addClass("active")    

```

and in css

```
.nav-menu-item.active{ ... }
```

**Comment by fma965** [comment]
He's likely to accept that if you send it as a PR (pull request)

**Comment by Hellowlol** [comment]
Yeah I will. Just make sure use use use the same color as the current theme hover or something. Some off the dark themes has that on the navbar

**Comment by thatbritguy** [comment]
Does that code force text in the page-header to lower case?  Don't think that should be imposed on people.

**Comment by Hellowlol** [comment]
No only the Ids that is used for navigation (they are hardcoded anyway)
