### ISSUE TITLE
error freenas script

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#423]
@josh4trunks I didnt insufficient privileges to post on the forum. I cant remember what user have me the init script or where i found the script. If you could correct it it would be awesome.

https://forums.freenas.org/index.php?threads/htpc-manager.40531/#post-259364

**Comment by josh4trunks** [comment]
sure, I'll clone your repo, make some edits and submit a PR.

**Comment by josh4trunks** [comment]
I'm not sure what you'd want the source and data-directories to be. I'll assume /usr/local/share/HTPC-Manager and /var/db/htpc-manager, but feel free to tweak this.

Another issue is that in order to run this program as a non-root user we'd need that user to exist on the system. This command could do it...
`pw useradd -n media -u 816 -d /nonexistent -s /sbin/nologin`
