### ISSUE TITLE
HTPC / (root) Webdir location instead of /HTPC Webdir

### ISSUE THREAD

**Issue by WzL** [Hellowlol/HTPC-Manager#505]
### Reporting Issues:

I want HTPC to be the main webpage, without redirect by client browser, under my NGinx reverse proxy root / location say https://example.com/. All other apps are configured as sub locations in Nginx for example https://example.com/sickrage/ and https://example.com/nzbget/ etc.

When I configure HTPC-Manager as my root / location so default page under https://mydomain.com/, HTPC-Manager is not able to connect to the configured sub locations for example https://mydomain.com/sickrage/ or https://mydomain.com/couchpotato/. For example if i test the connection to NZBGET (127.0.0.1:6789) it fails. Connections only works when HTPC is configured using its own sub location like /HTPC. 

My assumption is that the HTPC-Manager is searching for these subdirectories within it's own webserver (Cherrypy?) and is not requesting the content from NginX reverse proxy. 

Question: is it possible to run HTPC on / (root) location (NginX reverse proxy) and add sub locations for all other apps?

**Comment by Hellowlol** [comment]
The request is handed over to cherrypy that searched the other paths. Since the modules are named /sickrage etc this will fail. I dont know its there is a way to fix it. I have worked around the issue by using using a subdomain for direct access to the services. 

You can drop direct access to nzbget etc and just enable the iframe option under general settings. It would look something like this.

https://cloud.githubusercontent.com/assets/1214134/14577728/f6225926-0377-11e6-868f-6e3f33693742.png

**Comment by WzL** [comment]
Ok thanks for your reply, not possible as sublocation. Workaround is applying subdomains. Thank you for the iframe headsup! Issue can be closed in my opinion!
