### ISSUE TITLE
Python 2 EOL - Jan 2020

### ISSUE THREAD

**Issue by jeremysherriff** [Hellowlol/HTPC-Manager#611]
Python 2.7 will reach End Of Life (EOL) in January 2020.
https://www.python.org/dev/peps/pep-0373/#update

Are there any intentions to update HTPC Manager to use Python 3?

**Comment by Hellowlol** [comment]
Honestly i hardly use HTPC Manager anymore so no. I dunno if other ppl are using it. Have you tried running it under py3?

**Comment by jeremysherriff** [comment]
Not recently, no.  From memory it complains about needing 2.7 but I might be getting confused with another project.

I know this project is no longer super-active so I completely expected this response.  My reason for posting a "formal" issue was in the hope that someone who knows what they are doing will stumble on it and take a look.  It's way outside my level of expertise.

**Comment by jeremysherriff** [comment]
PS; the OpenFLIXR project (www.openflixr.com) uses HTPC Manager by preference - we have almost 300 members in the discord support channel and they tend to be new users that need assistance with setup. I estimate around 5,000 active users.  The HTPC front end is definitely alive and appreciated.

**Comment by Hellowlol** [comment]
It shouldn't require to much effort to port the project, and there are tools that are available to that automatically handles the most common cases. I cant remember that i have used any features that isn't available in py3. However some dependencies might need a upgrade (files in /libs)

**Comment by gmiranda** [comment]
> 
> 
> It shouldn't require to much effort to port the project, and there are tools that are available to that automatically handles the most common cases. I cant remember that i have used any features that isn't available in py3. However some dependencies might need a upgrade (files in /libs)

I have just ported it over python 3, including the dependencies, but extensive testing is required. Would you consider a PR?

**Comment by Hellowlol** [comment]
Not really. I dont use htpc manger anymore. Maybe you can pickup the torch.

**Comment by gmiranda** [comment]
Fair enough. My python3 fork is at https://github.com/gmiranda/HTPC-Manager but I don't expect to maintain it actively.

**Comment by MichaIng** [comment]
@Hellowlol @gmiranda 
Probably it would be great if this repo could be turned into an organisation, so it does not depend on a single developers account but contributors can be easier included and "torch" token over without breaking the repository links that are used by end users, especially since gmiranda doesn't "expect to maintain it actively" 😉.

I think this repo can be turned into e.g. `https://github.com/HTPC-Manager/HTPC-Manager` and gmiranda added + given admin rights so that his own fork can be merged and `https://github.com/Hellowlol/HTPC-Manager` will be redirected automatically, hence URL stays intact, including the the related code parts (updater).

What do you think?

I'm interested since our project [DietPi](https://github.com/MichaIng/DietPi) offers HTPC Manager as ready-to-run install option and we aim to migrate everything from Python 2 to Python 3 where possible and add Debian Bullseye support, where Python 2 is not available anymore. We have a few hundred users/systems with HTPC Manager installed, and a few reports/requests around it handled, so there is obviously interest in the HTPC Manager project and possibly contributors or at least testers among our user base. I can do a call for help to push it a bid and make users aware of required testers and contributors to keep it alive and compatible with modern systems.

**Comment by MichaIng** [comment]
Okay https://github.com/HTPC-Manager/HTPC-Manager is now a fork from https://github.com/gmiranda/HTPC-Manager, however that is the best we can do.
Turning https://github.com/Hellowlol/HTPC-Manager into an organisation repo would have meant to turn `Hellowlol` into an organisation which is of course not wanted, I was not thinking well through it 😄.
